In [2]:
import tmrl
import time
import matplotlib.pyplot as plt
import numpy as np
import torch

In [4]:
np.arange(64).reshape((8,8))[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
torch.cuda.is_available()

True

In [6]:
env = tmrl.get_environment()
time.sleep(1)

In [7]:
env.action_space

Box(-1.0, 1.0, (3,), float32)

In [8]:
env.observation_space

Tuple(Box(0.0, 1000.0, (1,), float32), Box(0.0, inf, (4, 19), float32), Box(-1.0, 1.0, (3,), float32), Box(-1.0, 1.0, (3,), float32))

In [15]:
obs, info = env.reset()

C:\Users\xande\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\rtgym\envs\real_time_env.py:376: UserWarning: Time-step timed out. Elapsed since last time-step: 10.257195700018201
  warnings.warn(f"Time-step timed out. Elapsed since last time-step: {now - self.__t_end}")


In [13]:
env.wait()

In [14]:
env.step(np.array([1,0,0]))

((array([0.], dtype=float32),
  array([[457.,  30.,  22.,   9.,   0.,   5.,   9.,   5.,   5.,   4.,   0.,
            5.,   3.,   2.,   1.,   7.,  21.,  32., 458.],
         [457.,  30.,  22.,   9.,   0.,   5.,   9.,   5.,   5.,   4.,   0.,
            5.,   3.,   2.,   1.,   7.,  21.,  32., 458.],
         [457.,  30.,  22.,   9.,   0.,   5.,   9.,   5.,   5.,   4.,   0.,
            5.,   3.,   2.,   1.,   7.,  21.,  32., 458.],
         [457.,  30.,  22.,   9.,   0.,   5.,   9.,   5.,   5.,   4.,   0.,
            5.,   3.,   2.,   1.,   7.,  21.,  32., 458.]], dtype=float32),
  array([0., 0., 0.], dtype=float32),
  array([1, 0, 0])),
 0.0,
 False,
 False,
 {})

In [ ]:
env.action_space

In [ ]:
env.observation_space

In [ ]:
env.close()

In [ ]:
import gym
from gym import spaces

In [ ]:
lower_bound = np.array([-1, -1, -3])
upper_bound = np.array([1, 1, 3])
observation_space = spaces.Box(low=lower_bound, high=upper_bound)

In [ ]:
observation_space

In [ ]:
env.action_space.sample()

In [ ]:
env.observation_space.sample()